<?php
$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'importit importit-sources import');
$form->prepare();
?>

<?php echo $this->pageTitle($source->name(), 1, $translate('Import It'), $translate('Import')); ?>
<?php echo $this->trigger('view.import.before'); ?>
<?php echo $this->form()->openTag($form); ?>
<?php $this->trigger('view.import.form.before', ['form' => $form]); ?>
<div id="page-actions">
    <?= $this->hyperlink($translate('Cancel'), $this->url('admin/importit/source'), ['class' => 'button']) ?>
    <button><?php echo $translate('Start import'); ?></button>
</div>
<?php echo $this->formCollection($form, false); ?>
<?php $this->trigger('view.import.form.after', ['form' => $form]); ?>
<?php echo $this->form()->closeTag(); ?>

<?php $this->trigger('view.import.after'); ?>
